# Работа с исключениями 
## 1) Перехват всех исключений
Все исключения наследованны от класса `Exception`;  
Обработка исключений  

	try 
	{
		// Делаем что-то опасное
	}
	catch(Excpetion e)
	{
		// В этот блок программа попадёт при выбрасывания исключения
		// Обрабатываем исключение. 
	}

## 2) finally
Блок `finally` идёт после всех блоков `catch`. В блок `finally` программа попадёт либо после выполнения блока `try`, либо после обработки ошибки.

	try 
	{}
	catch(Exception) {}
	finally
	{
	}

## 3) Несколько catch
Несколько catch должны стоять в порядке от потомка к предку

	class A : Exception {}
	class B : A {}
	class C : B {}

	//...

	public static void Main(string[] args)
	{
		Random rand = new Random();
		var randomNum = rand.Next(1,4);
		try 
		{
			switch(randomNum)
			{
				case 1:
					throw new C();
					break;
				case 2:
					throw new B();
					break;
				case 3:
					throw new A();
					break;
			}
		}
		catch(C) {...}
		catch(B) {...}
		catch(A) {...}
		finally {...}
	}
